pipeline {
    agent any
    
    environment {
        MONGODB_URI = '' // Define the environment variable to hold MongoDB URI
    }
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Abdur1Rafae/iba-gke-cicd'
            }
        }
        stage('Set MongoDB URI') {
            steps {
                withCredentials([string(credentialsId: 'MONGODB_URI', variable: 'MONGODB_URI')]) {
                    script {
                        env.MONGODB_URI = MONGODB_URI
                    }
                }
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        // stage('Deploy to Minikube') {
        //     steps {
        //         sh 'kubectl apply -f k8/'
        //     }
        // }
    }
}
